### ISSUE TITLE
Discover Go and JS nodes

### ISSUE THREAD

**Issue by adamski** [dvc94ch/rust-ipfs#1]
I believe this requires adding an mDNS implementation that is compatible with the Go and JS nodes. Not sure if this should be addressed in an IPFS implementation or in rust-libp2p.

**Comment by dvc94ch** [comment]
@adamski there's no hurry with this, this IPFS implementation won't be useful for a while...

**Comment by gnunicorn** [comment]
@adamski this requires fixes/changes in the libp2p stack. see https://github.com/libp2p/rust-libp2p/pull/968

**Comment by dvc94ch** [comment]
Adding an Identify behaviour fixed the connection problems with jsipfs. Let me know if you are still running into issues...

**Comment by dvc94ch** [comment]
Looks like this issue can be closed.
