### ISSUE TITLE
DataStore should be modular

### ISSUE THREAD

**Issue by adamski** [dvc94ch/rust-ipfs#31]
DataStore is currently using RocksDB. This is probably fine for a lot of use cases, but for example on iOS it might be preferable to use Core Data, or elsewhere SQLite. 

DataStore should be modular, so the user can choose between different underlying stores.

**Comment by dvc94ch** [comment]
Can you elaborate what's wrong with the existing way of doing this? You can implement a custom struct with IpfsTypes and use that when creating an ipfs instance.

**Comment by adamski** [comment]
Thanks for the info - I made an assumption based on looking at the code. I'm not super fluent in Rust yet. Good to know its possible.
