### ISSUE TITLE
Drop nightly requirement

### ISSUE THREAD

**Issue by koivunej** [dvc94ch/rust-ipfs#36]
Moving to stable would allow us to keep up to date easier, and allow tools like [`skeptic`](https://crates.io/crates/skeptic) and compile the README.md example automatically. Currently there is only single feature being used: `try_trait` which could be replaced [`void`](https://crates.io/crates/void) which is already part of the dependency tree.

**Comment by austinsheep** [comment]
For replacing `try_trait` with `void`, would the error cases for the `impl TryInto/TryFrom`'s instead call `unreachable!()`?

**Comment by koivunej** [comment]
Here was a comment asking about this the `void` hint. Could be that I've misunderstood the current use of `try_trait` and the suggestion to replace it with a `void::Void` is wrong. Could be that a simple error enum or empty struct would work here better.

**Comment by dvc94ch** [comment]
I agree, now that async await is stable, we should drop the nightly requirement

**Comment by koivunej** [comment]
Implemented in #39
